### PR TITLE
Issue #370 Add test story to check cluster health

### PR DESCRIPTION
**Pull request by jsliacan**
The user starts CRC, logs in to the cluster, creates project, creates app, waits for it, exposes it, then tries to reach the app. Afterwards deletes the project and stops & deletes CRC.

### CODE REVIEW

**Comment by jsliacan** [comment]
retest this please

**Comment by praveenkumar** [comment]
retest this please

**Comment by anjannath** [comment]
retest this please

**Comment by jsliacan** [comment]
retest this please

**Comment by jsliacan** [comment]
retest this please

**Comment by jsliacan** [comment]
retest this please

**Comment by jsliacan** [comment]
retest this please

**Comment by jsliacan** [comment]
@praveenkumar @gbraad I retested this multiple times but cannot get the error to show up again (see below for the error). I'm leaving `--log-level debug` option in there in case error shows up after this is merged. Otherwise I think the PR is finalised -- unless you can still spot something. Thanks!
```
14:39:07.789787  stdout: CodeReady Containers instance is running
14:39:07.790201  stdout: exitCodeOfLastCommandInShell=0
14:39:07.790288    bash: eval $(crc oc-env)
14:39:07.801129  stdout: exitCodeOfLastCommandInShell=0
14:39:07.801262    bash: oc login --insecure-skip-tls-verify -u kubeadmin -p 9gZtH-EWZLT-mZNFP-bkKwm https://api.crc.testing:6443
14:39:07.938056  stderr: Error from server (InternalError): Internal error occurred: unexpected response: 503
```

**Comment by gbraad** [comment]
@tsedmik Please have a look... If approved I can merge.

**Comment by jsliacan** [comment]
retest this please

**Pull request merged**
