### PR TITLE
podman:generate new random bearer token for cockpit

### LINKED ISSUE #2890: [Task] Unique bearer token to allow cockpit login (podman preset)
When the podman preset is used, the user should be able to login using a unique bearer token. At the moment the token has been statically defined as mentioned in https://github.com/code-ready/snc/pull/494/files#r771795733. Once the image is started, a unique `base64` encoded value should be used; this would be generated by `crc` and stored inside the VM, and used by tray-electron as the bearer authentication method.

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #2890 

Depends on https://github.com/code-ready/snc/pull/500

### CODE REVIEW

**Review by gbraad — APPROVED** [review]

**Review by gbraad — APPROVED** [review]

**Comment by praveenkumar** [comment]
@anjannath `go fmt` is failing on the CI side.

**Comment by anjannath** [comment]
@praveenkumar fixed the `gofmt` issues

**Pull request merged**
