### PR TITLE
Issue #400 Add sha256sum to the final release binaries

### LINKED ISSUE #400: Add sha256sum for make cross and also for release makefile target.
Right now, we are not creating the sha256sum for the cross builds and also for the release target in the Makefile, which we mostly require.

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #400 #449

### CODE REVIEW

**Comment by gbraad** [comment]
@code-ready/crc-devel WDYT?

**Comment by cfergeau** [comment]
A single file with hashes for all files seems fairly typical, so yes, makes sense.

**Comment by praveenkumar** [comment]
@gbraad @cfergeau If you check odo/oc directory structure it make sense since they are putting every bits in the same root directory but we want to put in different directory as per binary (like macos, linux, windows) so I think to have that for each dir binary may be better than having it on top directory in a single file?

**Comment by gbraad** [comment]
The point would be, we aren't linking to the sha256 file from the landing page. So separation does not make a lot of sense. This is a service for advanced users ... or to describe in the troubleshooting guide. So, I do think a single file still makes more sense.

**Comment by gbraad** [comment]
>  but we want to put in different directory as per binary (like macos, linux, windows)

No... The suggestion was to name files `crc-windows.zip`, `crc-macos.tar.gz`, and `crc-linux.tar.gz` and the folder would be versioned and collection all the deliverables.

**Comment by anjannath** [comment]
You can also probably take care of #449 here!

**Pull request merged**
