### PR TITLE
Update admin-helper: it is not compressed twice anymore

### PR DESCRIPTION
**Pull request by guillaumerose**
Also move the root check first.

### CODE REVIEW

**Comment by praveenkumar** [comment]
Can you elaborate on https://github.com/code-ready/crc/pull/1835/commits/54dd7ce4aca4236d58f936855a2f53dd9c55a83a one, like what is current scenario and after this patch what it would be?

**Comment by guillaumerose** [comment]
I added more details. Basically, if I'm root, podman-remote, etc binaries will be created in /root/.crc/bin and then crc will refuse to continue with the root check.

**Comment by praveenkumar** [comment]
> I added more details. Basically, if I'm root, podman-remote, etc binaries will be created in /root/.crc/bin and then crc will refuse to continue with the root check.

This is much better than you put in the commit log :)

**Pull request merged**
