### PR TITLE
Bump openshift vendoring from 4.5 to 4.6

### PR DESCRIPTION
**Pull request by guillaumerose**
Using this https://github.com/openshift/oc/blob/release-4.6/go.mod as
reference.

Vendoring needs to be kept in sync with openshift version contained in the bundle.

### CODE REVIEW

**Comment by cfergeau** [comment]
Not sure it's strictly required that we vendor the 4.6 code if we are not using 4.6 specific features, but it's definitely more consistent this way.
\lgtm

**Review by cfergeau — COMMENTED** [review]
`vendor/` grows by 7% / 2MB

**Review by cfergeau — APPROVED** [review]

**Review by cfergeau — APPROVED** [review]
Still looks good to me, unclear what the CI failures are :(

**Comment by guillaumerose** [comment]
I rebased it, in case it's better.

**Pull request merged**
