### PR TITLE
macos: Add disk resizing support

### PR DESCRIPTION
**Pull request by cfergeau**
This requires a new machine-driver-hyperkit release (+ the merge of the
corresponding PR) before it works.

**Fixes:** https://github.com/code-ready/crc/issues/1640 

## Testing

1. After this PR, and with a matching machine driver, crc start --disk-size xxx should work the same as on the other platforms

### CODE REVIEW

**Comment by praveenkumar** [comment]
/hold

I am testing it as user prospective, will merge after testing.

**Comment by guillaumerose** [comment]
Tested on macOS, works fine for me. 
The only issue was with the tray. The disk size parameter was not correctly passed. https://github.com/code-ready/crc/pull/2439

There is maybe an issue when upgrading: QcowToolPath won't be defined for old cluster. I didn't test that but we ask the user to delete before upgrade.

**Comment by praveenkumar** [comment]
/unhold

Tested and it works as expected.

/lgtm

**Comment by guillaumerose** [comment]
Can you do the driver release and include it in this PR ?

**Comment by praveenkumar** [comment]
> Can you do the driver release and include it in this PR ?

https://github.com/code-ready/crc/pull/2467 I put the PR for same.

**Pull request merged**
