### PR TITLE
Issue #1, #3 Basic structure

### LINKED ISSUE #1: Add basic command structure

### LINKED ISSUE #3: Add basic abstractions
Add abstractions for logging and output print (from structure)

possibly print json -> #13

### PR DESCRIPTION
**Pull request by gbraad**
Fixes #1,
Fixes #3

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I am going ahead and merging this, so that we can add Makefile and other pieces after this.

**Comment by LalatenduMohanty** [comment]
> I am going ahead and merging this, so that we can add Makefile and other pieces after this.

@gbraad I have some questions and suggestion around using a proper logging framework which I am planning discuss in another issue

**Comment by gbraad** [comment]
@LalatenduMohanty didn't want to decide just yet. especially as glog, logrus and others have been used before...

**Comment by gbraad** [comment]
other pieces needed are `Makefile`, `glide.yaml`, etc.

**Pull request merged**
