### PR TITLE
Update bundle version from 4.4.8 to 4.5.0-rc.5

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
> I assume nothing is confused by the -rc.5?

@cfergeau you mean not using the `rc` bits here or anything else?

**Comment by praveenkumar** [comment]
/hold 

Will also try to fix the operator test case with same PR.

**Comment by cfergeau** [comment]
> > I assume nothing is confused by the -rc.5?
> 
> @cfergeau you mean not using the `rc` bits here or anything else?

Not suggesting changing anything, just mentioning that I can't think of crc code which would be impacted/confused by the `-rc.5`

**Pull request merged**
