### PR TITLE
#2004 Extract then rename can be too fast for Windows antivirus

### PR DESCRIPTION
**Pull request by guillaumerose**
Add a retry loop as a temporary fix.

In the future we should this change to:
* read the first bytes of the bundle and get the manifest,
* find the bundle name and check if this bundle already exists,
* extract the bundle directly in the right directory, skipping the
directory structure of the archive.

Related to #2004

### CODE REVIEW

**Review by cfergeau — COMMENTED** [review]
Were you able to reproduce? Not really clear why being too fast is an issue?

**Review by gbraad — APPROVED** [review]
5 seconds is quite a lot between a retry. But let's see first. This is merely a workaround to begin with. You bad no comment on coffee to explain why

**Comment by gbraad** [comment]
> Were you able to reproduce? Not really clear why being too fast is an issue?

Not myself as I do not really on 3rd party tools. But this kinda a known thing.

**Comment by guillaumerose** [comment]
I asked users to give it a try. Let's wait a bit and see if it works.

**Comment by cfergeau** [comment]
> . But this kinda a known thing

I don't know about it, so this change just looks like magic to me :) What are the antivirus expectations wrt renames/how is slowing things down helping?

**Comment by guillaumerose** [comment]
@juhanevalainen told us it is working for him. Let's ship this in the next release.

**Pull request merged**
