### PR TITLE
Run `go mod tidy`. Remove unnecessary dependencies in go.mod and go.sum.

### PR DESCRIPTION
**Pull request by guillaumerose**
Minor cleanup. This was prompted by Jetbrains Goland when I opened the go.mod file.

I ran `go mod tidy` then `go mod vendor`. Vendor directory was already in a clean state, nothing changed.

### CODE REVIEW

**Comment by praveenkumar** [comment]
@guillaumerose Should we add a target in the Makefile and check in the CI also or make it part of `make vendor` because in future this will again happen.

**Comment by vdemeester** [comment]
> @guillaumerose Should we add a target in the Makefile and check in the CI also or make it part of `make vendor` because in future this will again happen.

@praveenkumar we do that on `tektoncd/cli` (and other tekton project) to validate that the vendor is always up-to-date :wink:

**Comment by guillaumerose** [comment]
I added `go mod tidy` in the Makefile. 

For the CI, the change is a little bit bigger. `go mod verify` doesn't still check the vendor/ directory. We need to have something like https://github.com/tektoncd/cli/blob/master/hack/verify-codegen.sh - should I copy this script ?

**Comment by praveenkumar** [comment]
> For the CI, the change is a little bit bigger. go mod verify doesn't still check the vendor/ directory. We need to have something like https://github.com/tektoncd/cli/blob/master/hack/verify-codegen.sh - should I copy this script ?

I agree we might need a script to fail the CI when vendor directory or the go.mod/sum doesn't match what it should be but that should be a different commit/PR.

**Comment by guillaumerose** [comment]
Looking at other way to do it, can we delete the vendor/ directory ? Is there a reason to keep it ? Number of dependencies is low and public.

**Comment by guillaumerose** [comment]
I added the script to verify the vendoring. PTAL.

**Comment by guillaumerose** [comment]
thanks for the merge!

**Pull request merged**
