### PR TITLE
[WIP] Print JSON status of preflight checks

### LINKED ISSUE #2935: Spike streaming JSON for `crc setup`.
When running `crc setup` information is streamed using `stdout` and only the end result is shown. This currently causes confusion, as messages like https://github.com/code-ready/crc/issues/2969 are shown; `you can now run 'crc start' to start`. This would direct a UI user to issue an unnecessary command from a command line.

It would be best to return the preflight and fixes from `crc setup` as a stream of JSON fragments, that can be interpreted by the tray/app and display instead of the command output. This is needed for code-ready/tray-electron#114

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #2935 

This is based on the initial changes done by @cfergeau at https://github.com/cfergeau/crc/commit/447677bd37c6c2ecf3c0055a799cbc7b86f005a8

```
## o/p of `crc setup`
PS C:\Users\anath\redhat\crc> crc setup --json-stream 2> txt
{
  "type": "check",
  "description": "Checking if current user is in Hyper-V Admins group",
  "result": "passed",
  "error": null
}
{
  "type": "check",
  "description": "Checking if CRC bundle is extracted in '$HOME/.crc'",
  "result": "failed",
  "error": {}
}
{
  "totalBytes": 650263232,
  "completedBytes": 255386044
}
{
  "totalBytes": 650263232,
  "completedBytes": 257664726
}
{
  "totalBytes": 650263232,
  "completedBytes": 260318934
}
```

### CODE REVIEW

**Comment by anjannath** [comment]
Please ignore the CI failure for now, is related to `gofmt` since am on windows these tools don't work properly

**Comment by gbraad** [comment]
Steps need to be identified by a number, especially a list of all these steps by name.
Else it is hard to relate what the deltas are for.

**Comment by anjannath** [comment]
> Steps need to be identified by a number, especially a list of all these steps by name. Else it is hard to relate what the deltas are for.

right now for every check/step this is the information that we get, you want an `id` to be included here that increments for step, what else should be included here?
```json
{
  "type": "check",
  "description": "Checking if current user is in Hyper-V Admins group",
  "result": "passed",
  "error": null
}
```
for the download, we get the total size and the currently downloaded size, which can be used for the progress bar on the tray. 

can you provide example of what should be the JSON o/p for `crc setup --json-stream` be?

**Comment by gbraad** [comment]
something like:
```
{
  "total": 20
},
{
  "id": 14.
  "type": "check",
  "description": "Checking if current user is in Hyper-V Admins group",
  "result": "passed",
  "error": null
}
{
  "id": 15,
  "type": "task",
  "description": "Downloading bundle",
},
{
  "belongto": 15,
  "totalBytes": 650263232,
  "completedBytes": 255386044
}
```

**Comment by anjannath** [comment]
@gbraad this is the updated o/p, not yet able to relate the download stats with the preflight check id, also in the code fix is part of the check struct, so even though the `id` is incremented, (since it only exists in the json printing part) the `total` key shows the no. of `Check{}` s 

```
PS C:\Users\anath\redhat\crc> crc setup --check-only --json-stream 2> txt
{
  "total": 2
}
{
  "id": 1,
  "type": "check",
  "description": "Checking if current user is in Hyper-V Admins group",
  "result": "passed",
  "error": null
}
{
  "id": 2,
  "type": "check",
  "description": "Checking if CRC bundle is extracted in '$HOME/.crc'",
  "result": "failed",
  "error": {}
}
```
-------
```
PS C:\Users\anath\redhat\crc> crc setup --json-stream 2> txt
{
  "total": 2
}
{
  "id": 1,
  "type": "check",
  "description": "Checking if current user is in Hyper-V Admins group",
  "result": "passed",
  "error": null
}
{
  "id": 2,
  "type": "check",
  "description": "Checking if CRC bundle is extracted in '$HOME/.crc'",
  "result": "failed",
  "error": {}
}
{
  "id": 3,
  "type": "fix",
  "description": "Getting bundle for the CRC executable",
  "result": "",
  "error": null
}
{
  "filename": "C:\\Users\\anath\\.crc\\cache\\crc_podman_hyperv_3.4.4.crcbundle",
  "totalBytes": 650263232,
  "completedBytes": 446963712
}
```

**Comment by gbraad** [comment]
Changing this to be newline delimited and add more information to the actual download message:

```
{
  "total": 26
}
{"id":1,"type":"check","description":"Checking if running as non-root","result":"passed","error":null}
{"id":2,"type":"check","description":"Checking if running inside WSL2","result":"passed","error":null}
{"id":3,"type":"check","description":"Checking if crc-admin-helper executable is cached","result":"passed","error":null}
{"id":4,"type":"check","description":"Checking for obsolete admin-helper executable","result":"passed","error":null}
{"id":5,"type":"check","description":"Checking if running on a supported CPU architecture","result":"passed","error":null}
{"id":6,"type":"check","description":"Checking minimum RAM requirements","result":"passed","error":null}
{"id":7,"type":"check","description":"Checking if crc executable symlink exists","result":"passed","error":null}
{"id":8,"type":"check","description":"Checking if Virtualization is enabled","result":"passed","error":null}
{"id":9,"type":"check","description":"Checking if KVM is enabled","result":"passed","error":null}
{"id":10,"type":"check","description":"Checking if libvirt is installed","result":"passed","error":null}
{"id":11,"type":"check","description":"Checking if user is part of libvirt group","result":"passed","error":null}
{"id":12,"type":"check","description":"Checking if active user/process is currently part of the libvirt group","result":"passed","error":null}
{"id":13,"type":"check","description":"Checking if libvirt daemon is running","result":"passed","error":null}
{"id":14,"type":"check","description":"Checking if a supported libvirt version is installed","result":"passed","error":null}
{"id":15,"type":"check","description":"Checking if crc-driver-libvirt is installed","result":"passed","error":null}
{"id":16,"type":"check","description":"Checking crc daemon systemd service","result":"passed","error":null}
{"id":17,"type":"check","description":"Checking crc daemon systemd socket units","result":"passed","error":null}
{"id":18,"type":"check","description":"Checking if systemd-networkd is running","result":"passed","error":null}
{"id":19,"type":"check","description":"Checking if NetworkManager is installed","result":"passed","error":null}
{"id":20,"type":"check","description":"Checking if NetworkManager service is running","result":"passed","error":null}
{"id":21,"type":"check","description":"Checking if dnsmasq configurations file exist for NetworkManager","result":"passed","error":null}
{"id":22,"type":"check","description":"Checking if the systemd-resolved service is running","result":"passed","error":null}
{"id":23,"type":"check","description":"Checking if /etc/NetworkManager/dispatcher.d/99-crc.sh exists","result":"passed","error":null}
{"id":24,"type":"check","description":"Checking if libvirt 'crc' network is available","result":"passed","error":null}
{"id":25,"type":"check","description":"Checking if libvirt 'crc' network is active","result":"passed","error":null}
{"id":26,"type":"check","description":"Checking if CRC bundle is extracted in '$HOME/.crc'","result":"failed","error":{}}
{"type":"download","filename":"/home/gbraad/.crc/cache/crc_podman_libvirt_3.4.4.crcbundle","totalBytes":649600569,"completedBytes":7437096}
{"type":"download","filename":"/home/gbraad/.crc/cache/crc_podman_libvirt_3.4.4.crcbundle","totalBytes":649600569,"completedBytes":33323816}
{"type":"download","filename":"/home/gbraad/.crc/cache/crc_podman_libvirt_3.4.4.crcbundle","totalBytes":649600569,"completedBytes":58620712}
{"type":"download","filename":"/home/gbraad/.crc/cache/crc_podman_libvirt_3.4.4.crcbundle","totalBytes":649600569,"completedBytes":84769576}
```

**Comment by gbraad** [comment]
Ideally this needs the step streamed BEFORE the result is known, and followed by the actual state is finished (passed/failed)

**Pull request closed without merging**
