### PR TITLE
#2446 Add USERDOMAIN prefix if the user is part of a domain

### PR DESCRIPTION
**Pull request by guillaumerose**
Second try. It works fine without a domain but I couldn't test with a domain.
I will ask users feedback with the AppVeyor build.

### CODE REVIEW

**Comment by anjannath** [comment]
Lint error... :( 
```
pkg/os/windows/win32/domains_windows.go:25:6: var-naming: don't use underscores in Go names; type Win32_ComputerSystem should be Win32ComputerSystem (revive)
type Win32_ComputerSystem struct {
     ^
make: *** [cross-lint] Error 1
```

**Comment by cfergeau** [comment]
it would be nice to expand the commit log a little bit, so that we don't have to follow the whole investigation of the issue to understand what this commit is about.

**Comment by adrianriobo** [comment]
Got this on `crc cleanup` after run the installer and `crc-setup` from this PR:

```bash
panic: Should not happen, empty description for cleanup 'check-crc-users-group-exists'

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/preflight.(*Check).doCleanUp(0xc0004ebb00, 0x0, 0x0)
        C:/gopath/src/github.com/code-ready/crc/pkg/crc/preflight/preflight.go:84 +0x179
github.com/code-ready/crc/pkg/crc/preflight.doCleanUpPreflightChecks(0xc0001c7000, 0x19, 0x27, 0xc0001c7000, 0x19)
        C:/gopath/src/github.com/code-ready/crc/pkg/crc/preflight/preflight.go:130 +0xbf
github.com/code-ready/crc/pkg/crc/preflight.CleanUpHost(0xc0004ebbe0, 0x47c053)
        C:/gopath/src/github.com/code-ready/crc/pkg/crc/preflight/preflight.go:182 +0x66
github.com/code-ready/crc/cmd/crc/cmd.runCleanup(0xc6603a8, 0x16978d8f968)
        C:/gopath/src/github.com/code-ready/crc/cmd/crc/cmd/cleanup.go:28 +0x2d
github.com/code-ready/crc/cmd/crc/cmd.glob..func1(0x2c89ce0, 0x31f56c0, 0x0, 0x0, 0xc0004ebcf0, 0x1)
        C:/gopath/src/github.com/code-ready/crc/cmd/crc/cmd/cleanup.go:23 +0x29
github.com/code-ready/crc/cmd/crc/cmd.executeWithLogging.func1(0x2c89ce0, 0x31f56c0, 0x0, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/code-ready/crc/cmd/crc/cmd/root.go:194 +0x141
github.com/spf13/cobra.(*Command).execute(0x2c89ce0, 0x31f56c0, 0x0, 0x0, 0x2c89ce0, 0x31f56c0)
        c:/gopath/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0x2c8ae60, 0xc0000340c0, 0x190f680, 0x31f56c0)
        c:/gopath/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        c:/gopath/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        c:/gopath/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/code-ready/crc/cmd/crc/cmd.Execute()
        C:/gopath/src/github.com/code-ready/crc/cmd/crc/cmd/root.go:107 +0x120
main.main()
        C:/gopath/src/github.com/code-ready/crc/cmd/crc/main.go:8 +0x27
```

**Comment by cfergeau** [comment]
There's a commit addressing this in https://github.com/code-ready/crc/pull/2502/commits

**Comment by adrianriobo** [comment]
Also during the `crc-setup` the domain user is not added to the `Hyper-V Adminsitrators group`. Other actions are done properly crc-users group creation + domain user added to the group.

`crc-setup` does not show any error, but checking the group from windows console the domain user is never added. Just to check I was able to add it with 

```powershell
Add-LocalGroupMember -Group 'Hyper-V Administrators' -Member domain\name
```

**Comment by anjannath** [comment]
> 
> 
> Also during the `crc-setup` the domain user is not added to the `Hyper-V Adminsitrators group`. Other actions are done properly crc-users group creation + domain user added to the group.
> 
> `crc-setup` does not show any error, but checking the group from windows console the domain user is never added. Just to check I was able to add it with
> 
> ```powershell
> Add-LocalGroupMember -Group 'Hyper-V Administrators' -Member domain\name
> ```

Seems to work for me in both cases, i was using the AzureAD service and user was added to both `Hyper-V admins` and `crc-users` group

**Comment by anjannath** [comment]
My tests were wrong, even though the machine is connected to AzureAD its not detected as a domain joined machine.. in the logs @adrianriobo pointed out that its just using the USERNAME portion..

Please add the DOMAIN part for addition to the hyperv group as well.
```
INFO Adding current user to group
DEBU Running 'Get-LocalGroupMember -Name crc-users -Member 'ChristieChan''
DEBU Command failed: exit status 1
DEBU stdout:
DEBU stderr: Get-LocalGroupMember : Principal ChristieChan was not found.
At line:1 char:43
+ ... yContinue'; Get-LocalGroupMember -Name crc-users -Member 'ChristieCha ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ChristieChan:String) [Get-LocalGroupMember], PrincipalNotFoundException
    + FullyQualifiedErrorId : PrincipalNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```

**Comment by guillaumerose** [comment]
@adrianriobo a fix has been merged for your issue. I rebased my PR, I hope it will be good this time.

**Comment by adrianriobo** [comment]
@guillaumerose I gave a run to latest bits and now it works well. (Did not have the change to test with hyper activation, as the guest machine has hyper v already enabled) but all user and group management with domain user is working fine

**Comment by anjannath** [comment]
> 
> 
> @guillaumerose I gave a run to latest bits and now it works well. (Did not have the change to test with hyper activation, as the guest machine has hyper v already enabled) but all user and group management with domain user is working fine.
> 
> Just find out after `crc cleanup` crc-users group has been deleted but domain user still on Hyper-V Administrators group (I signed off to check if sign off required, but even after that user was still there)

that's fine we don't remove user from the hyper-v admins group during cleanup, since it might have been added by some one else

**Review by anjannath — APPROVED** [review]

**Review by adrianriobo — APPROVED** [review]

**Comment by xgxtbku** [comment]
When will this get released? We struggling with the same issue. :(

**Comment by guillaumerose** [comment]
@xgxtbku This week. Most probably Wednesday.

**Comment by AlphaMalik** [comment]
Has this fix been released?

**Comment by praveenkumar** [comment]
@AlphaMalik It has been there for a long time.

**Comment by AlphaMalik** [comment]
Thanks @praveenkumar for the reply ... I am still getting this error though with this version of the CRC:
CRC version: 2.14.0+868d96cd

`
level=debug msg="stderr: Get-LocalGroupMember : Principal userid was not found.\r\nAt line:1 char:43\r\n+ ... yContinue'; Get-LocalGroupMember -Group 'crc-users' -Member 'userid ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (0B5293649:String) [Get-LocalGroupMember], PrincipalNotFoundException\r\n    + FullyQualifiedErrorId : PrincipalNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand\r\n \r\n"`

**Comment by cfergeau** [comment]
This could be related to https://github.com/crc-org/crc/issues/3282 https://github.com/crc-org/crc/pull/3523 but hard to tell without more details.
This will be part of the 2.15 release which should be coming out very soon.

**Comment by AlphaMalik** [comment]
Thanks @cfergeau for the reply
The issue is the same ... my userid in the Group membership has the domain thingee prefixed to it but crc is only querying for my userid portion only. 

> This could be related to #3282 #3523 but hard to tell without more details. This will be part of the 2.15 release which should be coming out very soon.

ahh .. that explains it ... this fix is not available in the most recent publicly available release of the crc which is 2.14 ... will wait for 2.15 release to come out.

**Pull request merged**
