### PR TITLE
go.mod: upgrade to github.com/mdlayher/vsock@v1.1.0

### PR DESCRIPTION
**Pull request by mdlayher**
Signed-off-by: Matt Layher <mdlayher@gmail.com>

**Fixes:** #3001.

**Relates to:** n/a.

## Solution/Idea

Upgrade to stable version of vsock with FileListener support. It seems this package also uses gvisor-tap-vsock, which I have also upgraded for the API change in v1.0.0 (see https://github.com/containers/gvisor-tap-vsock/pull/96). However I'm not sure how you want to handle that upgrade, so I will wait for further information since I don't think they have tagged a new release since the API change.

As-is this won't build, but it gets us a step closer to using the stable version.

## Proposed changes

See above.

## Testing

Not done, will need to coordinate the aforementioned upgrade.

### CODE REVIEW

**Comment by gbraad** [comment]
@cfergeau please have a look.

**Comment by mdlayher** [comment]
I bumped gvisor-tap-vsock to v1.1.0 this weekend too https://github.com/containers/gvisor-tap-vsock/pull/99. I can certainly go get that dependency at HEAD but I will defer to @cfergeau to explain how we want to proceed here.

**Comment by praveenkumar** [comment]
@mdlayher I can take care of this with #3002 one.

**Comment by praveenkumar** [comment]
@mdlayher cheery picked it here https://github.com/code-ready/crc/pull/3002/commits/a7865624fc9f5bce7436a578c56a2542cf0c04bd , we can close this one.

**Comment by mdlayher** [comment]
Thank you!

**Pull request closed without merging**
