### PR TITLE
Issue #898 Add proxy configuration to openshift-marketplace

### PR DESCRIPTION
**Pull request by praveenkumar**
Add proxy configuration to openshift-marketplace

### CODE REVIEW

**Comment by cfergeau** [comment]
> As of now all other operators which have config.openshift.io/inject-proxy
annotation get updated except marketplace when proxy resource is defined.

How do you check this? I tried to look at `oc get deployments --all-namespaces -o yaml`, find deployments with `inject-proxy`:
```
$  ~/.crc/bin/oc get deployment -n openshift-image-registry  -o yaml |grep inject-proxy
      config.openshift.io/inject-proxy: cluster-image-registry-operator
```

Then I looked at `oc get pods -n openshift-image-registry`, and then `oc debug pods/cluster-image-registry-operator-f9697f69d-mzcgb  -n openshift-image-registry` and `printenv` does not show a HTTP_PROXY variable defined even if it's there in `kubelet` environment.

Should I be testing this differently?

**Comment by praveenkumar** [comment]
> Then I looked at oc get pods -n openshift-image-registry, and then oc debug pods/cluster-image-registry-operator-f9697f69d-mzcgb -n openshift-image-registry and printenv does not show a HTTP_PROXY variable defined even if it's there in kubelet environment.

@cfergeau you can just check using `oc get pod <podname> -n openshift-image-registry -oyaml` to check the proxy env in the container spec, I think if you do `oc rsh <pod_name> -n openshift-image-registry` and then `env` or `printenv` should also list it.

**Comment by cfergeau** [comment]
> > Then I looked at oc get pods -n openshift-image-registry, and then oc debug pods/cluster-image-registry-operator-f9697f69d-mzcgb -n openshift-image-registry and printenv does not show a HTTP_PROXY variable defined even if it's there in kubelet environment.
> 
> @cfergeau you can just check using `oc get pod <podname> -n openshift-image-registry -oyaml` to check the proxy env in the container spec, I think if you do `oc rsh <pod_name> -n openshift-image-registry` and then `env` or `printenv` should also list it.

```sh
$ for name in $(oc get pods -n openshift-image-registry -oname); do oc get $name -n openshift-image-registry -oyaml |grep -i proxy; done
$
```

```sh
$ sudo cat /proc/$(pgrep -f kubelet)/environ
...HTTP_PROXY=http://squid.redhat.comHTTPS_PROXY=NO_PROXY=.cluster.local,.svc,10.128.0.0/14,172.30.0.0/16,127.0.0.1,localhost,.testing,192.168.130.11...
```

Proxy support is enabled in kubelet as far as I can tell, but is not propagated to the `openshift-image-registry` operator.

**Comment by cfergeau** [comment]
> Proxy support is enabled in kubelet as far as I can tell, but is not propagated to the `openshift-image-registry` operator.

This was a local issue, I was using an outdated crc binary which was setting an invalid no_proxy configuration. After recreating the cluster, it's better.

I looked again at the deployments with `inject-proxy` and at the corresponding pods, and now most of them have the proxy settings set.
One notable exception was `openshift-ingress`, but maybe that's expected.

I also tried `oc scale --replicas=1 -n openshift-insights deployment insights-operator` and then looked at `oc get pods -n openshift-insights -oyaml` and HTTP_PROXY is not set there.

So this PR feels like a short-term workaround for an issue we don't fully understand.
I don't necessarily object to adding this as a stop gap, but this will probably come back sooner or later :)

**Comment by praveenkumar** [comment]
retest this please.

**Comment by praveenkumar** [comment]
retest this please.

**Comment by cfergeau** [comment]
https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/resource/podtemplatespec.go#L105 might be why `openshift-image-registry` does the right thing wrt proxy.

**Comment by praveenkumar** [comment]
retest this please.

**Comment by praveenkumar** [comment]
retest this please.

**Comment by praveenkumar** [comment]
retest this please

**Pull request merged**
