### PR TITLE
Update bundle from 4.6.16 to 4.7.0

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
ok to test

**Comment by guillaumerose** [comment]
For enabling the monitoring stack, there is now 2 objects to activate: the CO object and the deployment.

**Comment by praveenkumar** [comment]
> or enabling the monitoring stack, there are now 2 objects to activate: the CO object and the deployment.

@guillaumerose Doesn't enablement of CO object also take care of the deployment or because deployment is also part of override so we need to explicit remove it?

**Comment by praveenkumar** [comment]
@guillaumerose When only removing the cluster operator kind ( https://github.com/code-ready/snc/blob/master/cvo-overrides.yaml#L8-L12 ) then monitoring appears  to `oc get co` output but it doesn't have any status but when you check
the resource definition, it does have `manager: cluster-version-operator`.

```
$ oc get co
NAME                                       VERSION      AVAILABLE   PROGRESSING   DEGRADED   SINCE
[...]
machine-approver                           4.7.0-rc.2   True        False         False      7d21h
marketplace                                4.7.0-rc.2   True        False         False      4m34s
monitoring                                                                                   
network                                    4.7.0-rc.2   True        False         False      7d21h
node-tuning                                4.7.0-rc.2   True        False         False      7d21h
```

But if we remove the deployment override ( https://github.com/code-ready/snc/blob/master/cvo-overrides.yaml#L3-L6 ) which is what we are currently doing then the monitoring does appear to `oc get co` output with it status but then the resource definition have `manager: operator` instead `cluster-version-operator` so we might need to remove both from override.

**Comment by gbraad** [comment]
We do not yet have a go to release with 4.7 due to https://bugzilla.redhat.com/show_bug.cgi?id=1927263

**Comment by gbraad** [comment]
We have a Go!

**Pull request merged**
