### PR TITLE
Remove obsolete code/factor some machine/bundle code a bit

### PR DESCRIPTION
**Pull request by cfergeau**
This should not cause any behaviour change, just removing some no longer useful code, or some c&p'ed code.

### CODE REVIEW

**Comment by praveenkumar** [comment]
Except the first commit we can have it in the dev branch which can be cherry-pick on the master also.

**Comment by cfergeau** [comment]
> Except the first commit 

Any suggestions how to improve it?

**Comment by cfergeau** [comment]
CI failures seem to be infra-related:
```
ERROR: gcloud crashed (SystemError): ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
If you would like to report this issue, please run the following command:
  gcloud feedback
To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics 
```

**Pull request merged**
