### PR TITLE
Update http example integration test

### PR DESCRIPTION
**Pull request by praveenkumar**
This patch will remove the check for deploymentconfig and deployment
which is causing issue for windows.

### CODE REVIEW

**Comment by gbraad** [comment]
@jsliacan @adrianriobo WDYT?

**Comment by adrianriobo** [comment]
This PR fix related problem described at https://github.com/code-ready/crc/issues/1785. This problem was produced due to inconsistent resources expectations, with this PR this is solved as we ensure only deployment is created and it covers the same functionality.. 

The only comment is what @guillaumerose suggested using an image based on [nginx](https://quay.io/repository/bitnami/nginx), it seems it would not change the expected http response code 403 but the image size is 1/3. 
```
IMAGE                                                   TAG                 IMAGE ID            SIZE
quay.io/bitnami/nginx                                   1.18.0              974152eb6fa49       93.3MB
registry.redhat.io/rhscl/httpd-24-rhel7                 latest              f6c37c3a78961       328MB
```

**Comment by gbraad** [comment]
> The only comment is what @guillaumerose suggested using an image based on [nginx](https://quay.io/repository/bitnami/nginx), it seems it would not change the expected http response code 403 but the image size is 1/3.

In short; approved?

**Comment by guillaumerose** [comment]
`quay.io/bitnami/nginx` has a default webpage, so it will be 200.

**Comment by adrianriobo** [comment]
If so, I would prefer go with quay.io/bitnami/nginx

**Review by jsliacan — COMMENTED** [review]
Others already commented on the `403` status code. Apart from that, we're using `1m` and `60s` for the same thing. This had been there before this PR, but let's align it at this opportunity - thanks!

**Comment by gbraad** [comment]
do we have something that exists in an OpenShift namespace?

**Comment by gbraad** [comment]
> 1m and 60s

I would prefer to see `1m`... and everything above should be possible in `1m 30` instead of `90s`... but enforcing this?
This is merely preference and more about maintainability... and should be for the whole test

**Pull request merged**
