### PR TITLE
fix docs_build job in circle ci

### PR DESCRIPTION
**Pull request by anjannath**
The error logs can be found at: https://circleci.com/gh/code-ready/crc/3325

### CODE REVIEW

**Comment by anjannath** [comment]
@cfergeau Yeah, we could wait for a bit, but this happened around late yesterday.. i hadn't seen the other error

**Comment by anjannath** [comment]
@cfergeau The `build_docs` job again failed today, https://app.circleci.com/pipelines/github/anjannath/crc/405/workflows/57f2f815-751e-4823-a6de-933cb36efce5/jobs/643
i don't think they're going to fix this, i'll try and open a bug report/issue on their tracker to get more details..

**Comment by cfergeau** [comment]
> @cfergeau The `build_docs` job again failed today, https://app.circleci.com/pipelines/github/anjannath/crc/405/workflows/57f2f815-751e-4823-a6de-933cb36efce5/jobs/643
> i don't think they're going to fix this, i'll try and open a bug report/issue on their tracker to get more details..

Yep, I've seen it as well a few days ago, since it seems to persist, we can get this in as a workaround and reevaluate when they close the bug report you open(ed)

**Comment by anjannath** [comment]
@cfergeau  will look at using a newer ubuntu image, or just a ruby image!

**Pull request merged**
