### PR TITLE
Adjust to new admin-helper naming

### LINKED ISSUE #2340: Change name of admin-helper binary to reflect origin/dependency
macOS/Darwin
https://github.com/code-ready/crc/blob/e4e58bf6e74d1fd26363f494b8d07981cb993e93/packaging/package.sh#L27

Windows
https://github.com/code-ready/crc/blob/e4e58bf6e74d1fd26363f494b8d07981cb993e93/packaging/windows/product.wxs.in#L50

Note: these names also include a platform identifier, which seems redundant and unnecessary for the actual platform it runs on. This seems more like an artifact of the build that happens.

### PR DESCRIPTION
**Pull request by cfergeau**
It's now `crc-admin-helper` rather than `admin-helper`. This PR should probably be held until there's a release of admin-helper with the new naming though.
I've only tested 'make release' on linux, hopefully the changes to the installers are good as well.

Fixes #2340 [Edit: added the issue number to auto-close]

## Proposed changes

List main as well as consequential changes you introduced or had to introduce.

1. The admin-helper binary in `~/.crc/bin` is now named `~/.crc/bin/crc-admin-helper-$OS`
2. If binaries named `admin-helper-$OS` are present in `~/.crc/bin/`, they are removed

### CODE REVIEW

**Comment by guillaumerose** [comment]
I published a release of admin-helper with the new name: https://github.com/code-ready/admin-helper/releases/tag/0.0.4

You can use it here.

**Comment by guillaumerose** [comment]
I updated the branch with the new binary. Let's see how it goes. https://github.com/code-ready/admin-helper/releases/tag/0.0.4

**Comment by guillaumerose** [comment]
/retest
retest this please

**Comment by guillaumerose** [comment]
works fine with the pkg. @anjannath if you can try the MSI

**Comment by anjannath** [comment]
> 
> 
> works fine with the pkg. @anjannath if you can try the MSI

Tested with msi and works fine!

**Review by anjannath — APPROVED** [review]

**Pull request merged**
