### PR TITLE
Include libmachine in crc repo

### PR DESCRIPTION
**Pull request by guillaumerose**
I had to fix tests and the linter. I removed couple of unused packages.

### CODE REVIEW

**Comment by gbraad** [comment]
> [APPROVALNOTIFIER] This PR is APPROVED
> This pull-request has been approved by: guillaumerose

?

**Comment by guillaumerose** [comment]
The approval is due to the new workflow. I guess it's because I'm in the owners list. If you add `/lgtm` I believe the bot will merge automatically. 
We can then avoid to add merge rights for everyone.

**Comment by guillaumerose** [comment]
I moved the commits related to the cleanup to https://github.com/code-ready/machine/pull/35 and created this PR by just two copy and two search and replace.

**Comment by guillaumerose** [comment]
Will do it in smaller steps

**Pull request closed without merging**
