### PR TITLE
Update bundle to 4.8.1 (candidate channel)

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
/hold

wait for green CI

**Comment by anjannath** [comment]
/retest
retest this please

**Comment by guillaumerose** [comment]
@praveenkumar looking at the last CI failure. 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/code-ready_crc/2599/pull-ci-code-ready-crc-master-e2e-crc/1418416371338842112

It is related to the generated bundle. When I look at the diagnose tarball, I see no containers schedueled. 
I am a little bit afraid of the kubelet error message:

```
Error reading manifest sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245 in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
```

I am wondering if it's related to the empty pull secret. 

Full kubelet message:

```
Jul 23 04:32:03 crc-vx258-master-0 hyperkube[2137]: E0723 04:32:03.995372    2137 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager_f2f24eb1-49c3-4dbf-945b-9504b4c6be72_0\": Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245: Error reading manifest sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245 in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized"
Jul 23 04:32:03 crc-vx258-master-0 hyperkube[2137]: E0723 04:32:03.995468    2137 kuberuntime_sandbox.go:68] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager_f2f24eb1-49c3-4dbf-945b-9504b4c6be72_0\": Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245: Error reading manifest sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245 in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized" pod="openshift-kube-controller-manager/kube-controller-manager-crc-vx258-master-0"
Jul 23 04:32:03 crc-vx258-master-0 hyperkube[2137]: E0723 04:32:03.995509    2137 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager_f2f24eb1-49c3-4dbf-945b-9504b4c6be72_0\": Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245: Error reading manifest sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245 in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized" pod="openshift-kube-controller-manager/kube-controller-manager-crc-vx258-master-0"
Jul 23 04:32:03 crc-vx258-master-0 hyperkube[2137]: E0723 04:32:03.995623    2137 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager(f2f24eb1-49c3-4dbf-945b-9504b4c6be72)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager(f2f24eb1-49c3-4dbf-945b-9504b4c6be72)\\\": rpc error: code = Unknown desc = error creating pod sandbox with name \\\"k8s_kube-controller-manager-crc-vx258-master-0_openshift-kube-controller-manager_f2f24eb1-49c3-4dbf-945b-9504b4c6be72_0\\\": Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245: Error reading manifest sha256:3ad7d07f2aab35ca7c819dc1b12820ad7986917b5f8299f3beab93def4ba5245 in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized\"" pod="openshift-kube-controller-manager/kube-controller-manager-crc-vx258-master-0" podUID=f2f24eb1-49c3-4dbf-945b-9504b4c6be72
````

**Comment by guillaumerose** [comment]
First CI failure is different. 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/code-ready_crc/2599/pull-ci-code-ready-crc-master-e2e-crc/1418240488137297920

MCO cannot set the pull secret because it is not correctly sync-ed.

```
E0722 17:03:17.168294    6593 daemon.go:1544] content mismatch for file "/var/lib/kubelet/config.json" (-want +got):
  bytes.Join({
- 	`{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2U`,
...
E0722 17:03:17.168398    6593 writer.go:135] Marking Degraded due to: unexpected on-disk state validating against rendered-master-3018c7173dadf8a766a6811f6b4cc2ff: content mismatch for file "/var/lib/kubelet/config.json"

```

**Pull request merged**
