### PR TITLE
Update default pull secret URL

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
retest this please.

**Comment by cfergeau** [comment]
Is this new page going to be available at a later time? For now, following https://cloud.redhat.com/openshift/install/crc/installer-provisioned I end up on a generic page offering me to choose between bare metal and various cloud providers. The old URL leads me to a page with installation instructions.

**Comment by praveenkumar** [comment]
@cfergeau you can check it with https://cloud.redhat.com/beta/openshift/install/crc/installer-provisioned until it is available soon.

**Comment by cfergeau** [comment]
I would either use the /beta/ URL for now, or delay merging this until the actual page is online.

**Comment by praveenkumar** [comment]
@cfergeau it is now online.

**Comment by anjannath** [comment]
Created https://github.com/code-ready/crc/issues/496 for this.

**Pull request merged**
