### PR TITLE
Fix disk resize with 4.7 bundles

### PR DESCRIPTION
**Pull request by cfergeau**
With 4.6 bundles, /dev/vda4 was automatically extended at startup to
fill unused disk space. This no longer happens in 4.7, possibly until
https://github.com/openshift/installer/pull/4746 is fixed.
This makes the xfs_growfs call in crc ineffective, as /dev/vda4 still
has its initial size.
This commit makes crc grow the partition itself until this bug is fixed.

This fixes https://github.com/code-ready/crc/issues/2104

### CODE REVIEW

**Comment by praveenkumar** [comment]
CI is failing with following, growpart fails if there is no additional space to grow so we might need add condition before running it or just add something to ignore it.

```
20:58:00 level=debug msg="Copying '/home/crc_ci/.crc/cache/crc_libvirt_4.7.2/kubeconfig' to '/home/crc_ci/.crc/machines/crc/kubeconfig'"
20:58:00 level=debug msg="Running SSH command: sudo /usr/bin/growpart /dev/vda 4 && sudo mount -o remount,rw /sysroot && sudo xfs_growfs /dev/vda4"
20:58:00 level=debug msg="SSH command results: err: Process exited with status 1, output: NOCHANGE: partition 4 is size 63961055. it cannot be grown\n"
20:58:00 level=debug msg="Making call to close driver server"
```

**Comment by cfergeau** [comment]
> CI is failing with following, growpart fails if there is no additional space to grow so we might need add condition before running it or just add something to ignore it.
> 
> ```
> 20:58:00 level=debug msg="Copying '/home/crc_ci/.crc/cache/crc_libvirt_4.7.2/kubeconfig' to '/home/crc_ci/.crc/machines/crc/kubeconfig'"
> 20:58:00 level=debug msg="Running SSH command: sudo /usr/bin/growpart /dev/vda 4 && sudo mount -o remount,rw /sysroot && sudo xfs_growfs /dev/vda4"
> 20:58:00 level=debug msg="SSH command results: err: Process exited with status 1, output: NOCHANGE: partition 4 is size 63961055. it cannot be grown\n"
> 20:58:00 level=debug msg="Making call to close driver server"
> ```

Forgot to test this case :( Thanks CI! Should be fixed now.

**Pull request merged**
