### PR TITLE
Add cleanup command to tests

### PR DESCRIPTION
**Pull request by jsliacan**
**Fixes:** Issue #1279 

**Relates to:** Issue # PR #

## Solution/Idea

Simply add the step to `basic.feature` file that uses `crc cleanup` to remove the relevant settings. Check the stdout against expected stdout. Then use `crc cleanup` through other feature files after the crux of the story is finished.

## Proposed changes

List main as well as consequential changes you introduced or had to introduce.

1. Modify `*.feature` files except for `config.feature`, where CRC is not started.

## Testing

What is the _bottom-line_ functionality that needs testing? Describe in pseudo-code or in English. Use verifiable statements that tie your changes to existing functionality.

1. Run `make integration` and all tests should pass, including the `crc cleanup` related steps.

### CODE REVIEW

**Comment by anjannath** [comment]
This would need updates, as the preflight/cleanups have changed

**Comment by jsliacan** [comment]
@anjannath - maybe I'll discard this PR (we're using cleanup command already, just not checking its output). I'll have to rework tests to follow the cucumber's progressively more enforced and restrictive design principles: https://github.com/cucumber/godog/issues/335. Basically every "Feature" needs to be crammed into a single Scenario. And each Scenario only has Steps as building blocks. So there won't be any space to check these individual outputs anymore (it's kind of unit-testish anyway).

**Comment by jsliacan** [comment]
@praveenkumar , the centos ci check did not pass, but one thing that didn't fail (when you open the console output) is the cleanup scenario :).

**Review by praveenkumar — APPROVED** [review]

**Pull request merged**
